# Modified version of the GitHub Action scripts from https://hexo.io/docs/github-pages
# Combined with the Jekyll starter workflow https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml,
# this script deploys Hexo sites to GitHub Pages
# without commiting them onto a branch.

# Original Licenses:
# - Hexo GH Script: CC BY 4.0 https://creativecommons.org/licenses/by/4.0/
# - Jekyll Script: MIT License https://github.com/actions/starter-workflows/blob/main/LICENSE

name: Deploy Hexo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main # default branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build with Hexo
        # Outputs to the './public' directory by default
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "public/"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
